server:
  port: 9090

spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      routes:

        - id: consumer-service
          uri: lb://CONSUMER-SERVICES
          predicates:
            - Path=/consumer/**
          filters:
            - name: CircuitBreaker
              args:
                name: consumerCircuitBreaker
                fallbackUri: forward:/fallback/consumer

        - id: login-service
          uri: lb://CONSUMER-SERVICES
          predicates:
            - Path=/login/**

        - id: transporter-service
          uri: lb://FLEET-HUB
          predicates:
            - Path=/transporter/**
          filters:
            - name: CircuitBreaker
              args:
                name: transporterCircuitBreaker
                fallbackUri: forward:/fallback/transporter


resilience4j:
  circuitbreaker:
    instances:
      transporterCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

      consumerCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s